### ISSUE TITLE
website down

### ISSUE THREAD

**Issue by PerspectivesLab** [flatlogic/react-dashboard#10]
the test demo page page isnt working : https://flatlogic-react-dashboard.herokuapp.com/

**Comment by okendoken** [comment]
@PerspectivesLab thanks for reporting! Yes, indeed it is not working. We are running on a free dyno which is over for this month. Since next month we will have different billing structure and it will be available all the time. 

Meanwhile I recommend you to clone the repo and launch it locally.

Please let me know if you have any other questions

**Comment by PerspectivesLab** [comment]
ok thx @okendoken !
